CREATE DATABASE IF NOT EXISTS APP;
CREATE DATABASE IF NOT EXISTS OWA   ;
CREATE USER IF NOT EXISTS app@'10.0.0.10' IDENTIFIED BY 'app';
CREATE USER IF NOT EXISTS owa@'10.0.0.13'IDENTIFIED BY 'owa';
GRANT ALL ON APP.* TO app@'10.0.0.10';
GRANT ALL ON OWA.* TO owa@'10.0.0.13';

