CREATE DATABASE IF NOT EXISTS APP;
CREATE DATABASE IF NOT EXISTS MATOMO;
CREATE USER IF NOT EXISTS app@'10.0.0.10' IDENTIFIED BY 'app';
CREATE USER IF NOT EXISTS matomo@matomo IDENTIFIED BY 'matomo';
GRANT ALL ON APP.* TO app@'10.0.0.10';
GRANT ALL ON MATOMO.* TO matomo@matomo;

