version: '3.7'
services:
  app:
    container_name: app
    build: ./app
    depends_on:
      - mysql
    ports:
      - "9000:9000"
      - "9999:9999"
    volumes:
      - "${DATA_LOCATION}/files:/mnt/data/files"
      - "../:/opt/source"
      - "~/.ivy2:/root/.ivy2"
    environment:
      - ENV=${ENV}
  mysql:
    container_name: mysql
    image: mysql:8.0.13
    ports:
      - "3306:3306"
    volumes:
      - "${DATA_LOCATION}/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD="root_password"
  nginx:
    container_name: nginx
    image: nginx:1.15.6
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      - NGINX_PORT=80
    
