version: '3.7'
services:
  app:
    container_name: app
    image: hdigiorgi/si_base:latest
    command: python main.py ${ENV} run
    depends_on:
      - mysql
    ports:
      - "9000:9000"
      - "9999:9999"
    volumes:
      - "${DATA_LOCATION}/files:/mnt/data/files"
      - "../:/opt/source"
      - "~/.ivy2:/root/.ivy2"
    environment:
      - ENV="${ENV}"
  mysql:
    container_name: mysql
    image: mysql:8.0.13
    ports:
      - "3306:3306"
    volumes:
      - "${DATA_LOCATION}/mysql:/var/lib/mysql"
      - "./mysql:/opt/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  nginx:
    container_name: nginx
    image: hdigiorgi/nginx_page_speed:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx.conf:/usr/local/nginx/conf/nginx.conf:ro"
      - type: tmpfs
        target: /dev/nginx_tmpfs
        tmpfs:
          size: 128000000 #128m
    
