version: '3.7'
services:
  app:
    container_name: app
    build: ./app
    ports:
      - "9000:9000"
      - "9999:9999"
    environment:
      - ENV=${ENV}
    volumes:
      - "${DATA_LOCATION}/files:/mnt/data/files"
      - "../:/opt/source"
      - "~/.ivy2:/root/.ivy2"
