CREATE DATABASE APP IF NOT EXISTS;
CREATE DATABASE MATOMO IF NOT EXISTS;
CREATE USER IF NOT EXISTS app@app IDENTIFIED BY 'app';
CREATE USER IF NOT EXISTS matomo@matomo IDENTIFIED BY 'matomo';
GRANT ALL ON APP.* TO app@app;
GRANT ALL ON MATOMO.* TO matomo@matomo;

