version: '3.7'
services:
  app:
    container_name: app
    image: hdigiorgi/si_base:latest
    command: python main.py ${ENV} run
    ports:
      - "9000:9000"
      - "9999:9999"
    volumes:
      - "${DATA_LOCATION}/files:/mnt/data/files"
      - "../../:/opt/source"
      - "~/.ivy2:/root/.ivy2"
    environment:
      - ENV="${ENV}"
    networks:
      internal:
        ipv4_address: 10.0.0.10
  nginx:
    container_name: nginx
    image: hdigiorgi/nginx_page_speed:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro"
      - "${DATA_LOCATION}/logs/:/dev/nginx_logs/"
      - type: tmpfs
        target: /dev/nginx_tmpfs
        tmpfs:
          size: 128000000 #128m
    networks:
      internal:
        ipv4_address: 10.0.0.11
    
networks:
  internal:
    ipam:
      config:
        - subnet: 10.0.0.0/24 